### ISSUE TITLE
Improve field extrapolation figure

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy-1.0-paper#137]
I suggest that the field lines be shown in white or another color. They blend too much into the background image especially in the lower right-hand corner.

**Comment by wtbarnes** [comment]
I think the main issue was with the transparency as I had set `alpha=0.4`. Here's black fieldlines with `alpha=0.6`. I think they stand out a bit better now.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/8676141/62839924-f4110700-bc46-11e9-83aa-3ed750c5ea5d.png">

 White blends in even worse because of the bright emission in the center of the AR, but red or blue could work. Just figured it'd be better to only add color if we have to.

**Comment by wtbarnes** [comment]
Here's blue with slightly reduced transparency (`alpha=0.5`). I'm fine with either.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/8676141/62839984-017ac100-bc48-11e9-9bf7-df7bdf61b7ea.png">
